### ISSUE TITLE
PHP 8.2 Fatal Error on Plugin Update – in_array() on null $hook_extra['plugins']

### ISSUE THREAD

**Issue by Aseela-Ali** [globalpayments/globalpayments-woocommerce#45]
Hi team,

Your plugin currently calls in_array() on $hook_extra['plugins'] during update actions without checking if it’s an array.

This causes a fatal error in PHP 8.2 when $hook_extra['plugins'] is null:

___Uncaught TypeError: in_array(): Argument #2 ($haystack) must be of type array, null given___

 **Affected lines:**
In both globalpayments_update_v110_v111() and globalpayments_update_plugin_version():

_in_array( plugin_basename( __FILE__ ), $hook_extra['plugins'] )_

**Suggested Fix:**
Please wrap the condition like this:

_! isset( $hook_extra['plugins'] ) || ! is_array( $hook_extra['plugins'] ) || ! in_array(...)_

This will make the plugin fully compatible with PHP 8.2+ and prevent fatal errors during plugin installation and updates.

Thanks — this will help many developers running modern PHP versions.

![Image](https://github.com/user-attachments/assets/b5c609e1-ddd3-4213-b5a8-5cf7df0d6b37)

**Comment by rerwin03** [comment]
@Aseela-Ali The team has reviewed this report and attempted to replicate but are unable to do so. Could you provide any additional context regarding your specific environment such as Wordpress version, WooCommerce version, our plugin version, and the steps used recreate? 

Thank you,

**Comment by Aseela-Ali** [comment]
Environment

Hosting: Nexcess (Apache/PHP-FPM)

PHP: 8.2.20

WordPress: 6.8.2

WooCommerce: 10.1.2

Theme: Divi Ecommerce (child of Divi)

GlobalPayments WooCommerce: 1.9.2 (patched locally for PHP 8.2 compatibility)

Also tested: latest release 1.13.8 from GitHub — same issue still present

**Steps to Reproduce (PHP 8.2 environment)**

In WP Admin, go to Plugins → Add New or update any existing plugin.

Install/update any plugin (example: Hello Dolly, Health Check, etc).

WordPress runs upgrader_process_complete.

Fatal error is triggered by the GlobalPayments plugin’s update hook.

**Actual Error**
Uncaught TypeError: in_array(): Argument #2 ($haystack) must be of type array, null given
in /wp-content/plugins/global-payments-woocommerce/globalpayments-gateway-provider-for-woocommerce.php:85

**Cause**
$hook_extra['plugins'] can sometimes be null in WP 6.8.x.
The plugin directly calls:
in_array(plugin_basename(__FILE__), $hook_extra['plugins'])

without ensuring the key exists and is an array.
Suggested Fix (safe for PHP 8.2+)
if (
    empty($hook_extra) ||
    'plugin' !== ($hook_extra['type'] ?? '') ||
    !isset($hook_extra['plugins']) ||
    !is_array($hook_extra['plugins']) ||
    !in_array(plugin_basename(__FILE__), $hook_extra['plugins'], true)
) {
    return;
}
This should be applied in both:

globalpayments_update_v110_v111()

globalpayments_update_plugin_version()

**Comment by rerwin03** [comment]
@Aseela-Ali The root cause has been identified and a patch is "dev complete". This change is under review internally. Once approved, the fix will be deployed. Pending no issues, you should anticipate a fix before the end of this week. A member of the team will follow up once the fix has been deployed.

**Comment by Aseela-Ali** [comment]
@rerwin-collab Thanks. I’ve tested the latest version on my staging site and can confirm that the original PHP 8.2 fatal error is resolved, the plugin now installs and updates without triggering the in_array() issue. Thank you for addressing this so quickly.

For awareness, the “Pay for Order” button issue (JS error in the admin order screen) is still present, but I understand that is already being tracked under issue [#44].

Thanks again for your support.
